name: create tag and release on merge pr

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  create-release:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20.x

      - name: set config tag and release
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")

          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"
          BODY_RELEASE="${PR_TITLE} ${PR_BODY}"

          echo "BODY_RELEASE<<EOF" >> $GITHUB_ENV
          echo "$BODY_RELEASE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          TAG_NAME="v${PACKAGE_VERSION}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

          RELEASE_NAME="Release v${PACKAGE_VERSION}"
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV

      - name: create tag and release
        uses: gabrielogregorio/create-tag-and-release@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          body: |
            ${{ env.BODY_RELEASE }}
          make_latest: true
          generate_release_notes: true
          draft: false
          prerelease: false
          discussion_category_name: 'Announcements'
